### LGBM:
1) запуск алгоритма с параметрами по умолчанию и вывод некоторой статистики
2) запуск optuna-оптимизации по части гиперпараметров
3) визуализация optuna: важность параметров и контуры
4) запуск алгоритма с найденными гиперпараметрами и вывод предварительной статистики
5) сохраняем результаты дефолтного и оптимизированного алгоритма

In [1]:
from private.utils import get_reduced_mnist_data, memory_check
from public.classification_utils import LGBM
from public.models import ClassificationProcessor

with memory_check():
    df = get_reduced_mnist_data()
    processor = ClassificationProcessor(df, "label")   
    processor.calculate({
        LGBM : {},
    })
    processor.report(LGBM)
    processor.pick_model(LGBM)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.140133 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 108649
[LightGBM] [Info] Number of data points in the train set: 56000, number of used features: 627
[LightGBM] [Info] Start training from score -2.316612
[LightGBM] [Info] Start training from score -2.184485
[LightGBM] [Info] Start training from score -2.304015
[LightGBM] [Info] Start training from score -2.282607
[LightGBM] [Info] Start training from score -2.328086
[LightGBM] [Info] Start training from score -2.405963
[LightGBM] [Info] Start training from score -2.320422
[LightGBM] [Info] Start training from score -2.261649
[LightGBM] [Info] Start training from score -2.327903
[LightGBM] [Info] Start training from score -2.308495

	light_gradient_boosting_machine

              precision  recall  f1-score   support
0                 0.983   0.991     0.987  1381.000
1                 0.985   0.982     0.983  1575.000
2                 0.976   0.977     0.976  1398.000
3                 0.964   0.968     0.966  1428.000
4                 0.976   0.968     0.972  1365.000
5                 0.979   0.966     0.972  1263.000
6                 0.983   0.983     0.983  1375.000
7                 0.976   0.975     0.975  1459.000
8                 0.965   0.973     0.969  1365.000
9                 0.954   0.957     0.955  1391.000
accuracy          0.974   0.974     0.974     0.974
macro avg         0.974   0.974     0.974 14000.000
weighted avg      0.974   0.974     0.974 14000.000

Memory Increased by: 0.88 MB

#### запуск optuna-оптимизации по части гиперпараметров

In [2]:
from public.optuna_utils import OPT_LGBM, optimize

with memory_check():
    study = optimize(
        model_type=OPT_LGBM, 
        df=df, 
        target_column="label",
        n_trials=50
    )
    print(f"Наилучшие значения гиперпараметров {study.best_params}")
    print(f"pr_auc на обучающем наборе: {study.best_value:.4f}")

[I 2026-08-17 19:19:25,980] A new study created in memory with name: Light Gradient-Boosting Machine

  0%|          | 0/50 [00:00<?, ?it/s]

Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
[10]	valid's multi_logloss: 0.575427 + 0.00306034	valid's macro_pr_auc: 0.98189 + 0.000837251
[10]	valid's multi_logloss: 0.77855 + 0.00233504	valid's macro_pr_auc: 0.979845 + 0.000682772
[10]	valid's multi_logloss: 0.581465 + 0.00307345	valid's macro_pr_auc: 0.982736 + 0.000800886
[10]	valid's multi_logloss: 0.597378 + 0.00265821	valid's macro_pr_auc: 0.982744 + 0.000772734
[10]	valid's multi_logloss: 0.714029 + 0.00280649	valid's macro_pr_auc: 0.981044 + 0.000720744
[10]	valid's multi_logloss: 0.843828 + 0.00201617	valid's macro_pr_auc: 0.980782 + 0.000646704
[10]	valid's multi_logloss: 0.64723 + 0.00245635	valid's macro_pr_auc: 0.982823 + 0.000610822
[10]	valid's multi_logloss: 0.806857 + 0.00229866	valid's macro_pr_auc: 0.981473 + 0.00074708
[10]	valid's multi_logloss: 0.604845 + 0.00279402	valid's macro_pr_auc: 0.983297 + 0.000729501
[10]	valid's multi_logloss: 0.682669 + 0.00253414	valid's macro_pr_auc: 0.982504 + 0.000741992
[10]	valid's multi_logloss: 0.576396 + 0.00322378	valid's macro_pr_auc: 0.983604 + 0.000914128
[10]	valid's multi_logloss: 0.75791 + 0.00235063	valid's macro_pr_auc: 0.982131 + 0.000621512
[20]	valid's multi_logloss: 0.271662 + 0.00377992	valid's macro_pr_auc: 0.988763 + 0.000671494
[20]	valid's multi_logloss: 0.403837 + 0.0034796	valid's macro_pr_auc: 0.986452 + 0.000576635
[20]	valid's multi_logloss: 0.357738 + 0.00379711	valid's macro_pr_auc: 0.987409 + 0.000587145
[20]	valid's multi_logloss: 0.272773 + 0.00273806	valid's macro_pr_auc: 0.989215 + 0.000450751
[20]	valid's multi_logloss: 0.281655 + 0.00300992	valid's macro_pr_auc: 0.989138 + 0.000486828
[20]	valid's multi_logloss: 0.450733 + 0.00280631	valid's macro_pr_auc: 0.986837 + 0.000607683
[20]	valid's multi_logloss: 0.421712 + 0.00299706	valid's macro_pr_auc: 0.987414 + 0.000611355
[20]	valid's multi_logloss: 0.311016 + 0.00322092	valid's macro_pr_auc: 0.988948 + 0.000451828
[20]	valid's multi_logloss: 0.28437 + 0.00287715	valid's macro_pr_auc: 0.989465 + 0.000474218
[20]	valid's multi_logloss: 0.333409 + 0.00361263	valid's macro_pr_auc: 0.988655 + 0.000532937
[20]	valid's multi_logloss: 0.385437 + 0.00330774	valid's macro_pr_auc: 0.98795 + 0.000573296
[20]	valid's multi_logloss: 0.267833 + 0.00310504	valid's macro_pr_auc: 0.989744 + 0.000480135
[30]	valid's multi_logloss: 0.169016 + 0.0039673	valid's macro_pr_auc: 0.992178 + 0.000505491
[30]	valid's multi_logloss: 0.25043 + 0.00350421	valid's macro_pr_auc: 0.989906 + 0.000445111
[30]	valid's multi_logloss: 0.219758 + 0.00354447	valid's macro_pr_auc: 0.990908 + 0.000424646
[30]	valid's multi_logloss: 0.167932 + 0.00276455	valid's macro_pr_auc: 0.99246 + 0.000293449
[30]	valid's multi_logloss: 0.172995 + 0.0026524	valid's macro_pr_auc: 0.992314 + 0.000337616
[30]	valid's multi_logloss: 0.279797 + 0.00333944	valid's macro_pr_auc: 0.989888 + 0.000490958
[30]	valid's multi_logloss: 0.259231 + 0.00337365	valid's macro_pr_auc: 0.990488 + 0.000414905
[30]	valid's multi_logloss: 0.189245 + 0.00278047	valid's macro_pr_auc: 0.992042 + 0.000291723
[30]	valid's multi_logloss: 0.173209 + 0.0029295	valid's macro_pr_auc: 0.992489 + 0.000364929
[40]	valid's multi_logloss: 0.125317 + 0.00364074	valid's macro_pr_auc: 0.994058 + 0.000388381
[30]	valid's multi_logloss: 0.202206 + 0.00329458	valid's macro_pr_auc: 0.991788 + 0.000384667
[40]	valid's multi_logloss: 0.176914 + 0.00336647	valid's macro_pr_auc: 0.992223 + 0.000323585
[30]	valid's multi_logloss: 0.235204 + 0.00321567	valid's macro_pr_auc: 0.991024 + 0.00035182
[40]	valid's multi_logloss: 0.156483 + 0.00302223	valid's macro_pr_auc: 0.993031 + 0.000319409
[30]	valid's multi_logloss: 0.164323 + 0.00278736	valid's macro_pr_auc: 0.992731 + 0.000329019
[40]	valid's multi_logloss: 0.124033 + 0.00239624	valid's macro_pr_auc: 0.994211 + 0.000237214
[40]	valid's multi_logloss: 0.126756 + 0.00256873	valid's macro_pr_auc: 0.994121 + 0.000259798
[40]	valid's multi_logloss: 0.195209 + 0.0032765	valid's macro_pr_auc: 0.992065 + 0.000388461
[40]	valid's multi_logloss: 0.181099 + 0.00313707	valid's macro_pr_auc: 0.992517 + 0.000300835
[50]	valid's multi_logloss: 0.103508 + 0.0031955	valid's macro_pr_auc: 0.995119 + 0.000287531
[40]	valid's multi_logloss: 0.136077 + 0.00236276	valid's macro_pr_auc: 0.993873 + 0.000221007
[50]	valid's multi_logloss: 0.138515 + 0.00283246	valid's macro_pr_auc: 0.993658 + 0.000242624
[50]	valid's multi_logloss: 0.12398 + 0.00271192	valid's macro_pr_auc: 0.994325 + 0.00024892
[40]	valid's multi_logloss: 0.126256 + 0.00255432	valid's macro_pr_auc: 0.994201 + 0.000222886
[40]	valid's multi_logloss: 0.143926 + 0.00302409	valid's macro_pr_auc: 0.993609 + 0.000313591
[40]	valid's multi_logloss: 0.165112 + 0.00287395	valid's macro_pr_auc: 0.992999 + 0.000273371
[50]	valid's multi_logloss: 0.102213 + 0.00220074	valid's macro_pr_auc: 0.995211 + 0.000190875
[40]	valid's multi_logloss: 0.121178 + 0.00255797	valid's macro_pr_auc: 0.99434 + 0.000221401
Did not meet early stopping. Best iteration is:
[56]	valid's multi_logloss: 0.123766 + 0.00261407	valid's macro_pr_auc: 0.994286 + 0.000201673
optuna_optimize took 6770.903 seconds
[I 2026-08-17 21:12:18,072] Trial 11 finished with value: 0.994286300563539 and parameters: {'n_estimators': 56, 'learning_rate': 0.0584194956270892, 'num_leaves': 68}. Best is trial 11 with value: 0.994286300563539.
Training until validation scores don't improve for 50 rounds
[50]	valid's multi_logloss: 0.103846 + 0.00198182	valid's macro_pr_auc: 0.995151 + 0.000163734
Did not meet early stopping. Best iteration is:
[57]	valid's multi_logloss: 0.110038 + 0.00244299	valid's macro_pr_auc: 0.994934 + 0.000210023
[60]	valid's multi_logloss: 0.0910156 + 0.00294275	valid's macro_pr_auc: 0.995787 + 0.000231957
Did not meet early stopping. Best iteration is:
[60]	valid's multi_logloss: 0.0910156 + 0.00294275	valid's macro_pr_auc: 0.995787 + 0.000231957
optuna_optimize took 6932.574 seconds
[I 2026-08-17 21:14:58,695] Trial 5 finished with value: 0.994933725631042 and parameters: {'n_estimators': 57, 'learning_rate': 0.0644523350055993, 'num_leaves': 71}. Best is trial 5 with value: 0.994933725631042.
optuna_optimize took 6939.735 seconds
[I 2026-08-17 21:15:06,207] Trial 4 finished with value: 0.9957873359780282 and parameters: {'n_estimators': 60, 'learning_rate': 0.08171714101609136, 'num_leaves': 65}. Best is trial 4 with value: 0.9957873359780282.
Training until validation scores don't improve for 50 rounds
Training until validation scores don't improve for 50 rounds
[50]	valid's multi_logloss: 0.149824 + 0.00297303	valid's macro_pr_auc: 0.993485 + 0.000279533
[50]	valid's multi_logloss: 0.139692 + 0.00278531	valid's macro_pr_auc: 0.993854 + 0.000237701
[50]	valid's multi_logloss: 0.109812 + 0.0022849	valid's macro_pr_auc: 0.994945 + 0.000177257
[10]	valid's multi_logloss: 0.82947 + 0.00200902	valid's macro_pr_auc: 0.978965 + 0.000770376
[10]	valid's multi_logloss: 0.837586 + 0.00205193	valid's macro_pr_auc: 0.978758 + 0.000807976
[50]	valid's multi_logloss: 0.114689 + 0.0028496	valid's macro_pr_auc: 0.994744 + 0.000247416
[50]	valid's multi_logloss: 0.103206 + 0.00246154	valid's macro_pr_auc: 0.995202 + 0.000191871
[60]	valid's multi_logloss: 0.0898889 + 0.00236659	valid's macro_pr_auc: 0.995851 + 0.000176385
[50]	valid's multi_logloss: 0.128883 + 0.00256731	valid's macro_pr_auc: 0.994229 + 0.000225816
[10]	valid's multi_logloss: 0.817356 + 0.0022475	valid's macro_pr_auc: 0.98117 + 0.000722068
[60]	valid's multi_logloss: 0.0911298 + 0.00181765	valid's macro_pr_auc: 0.995797 + 0.000111313
[50]	valid's multi_logloss: 0.100222 + 0.00204407	valid's macro_pr_auc: 0.995277 + 0.000124838
[60]	valid's multi_logloss: 0.123558 + 0.00286893	valid's macro_pr_auc: 0.994437 + 0.000230776
[20]	valid's multi_logloss: 0.44272 + 0.00316577	valid's macro_pr_auc: 0.985713 + 0.000660449
[60]	valid's multi_logloss: 0.0951312 + 0.00224256	valid's macro_pr_auc: 0.995624 + 0.000161581
[60]	valid's multi_logloss: 0.116171 + 0.00257402	valid's macro_pr_auc: 0.994733 + 0.000194403
[20]	valid's multi_logloss: 0.44877 + 0.00324757	valid's macro_pr_auc: 0.985611 + 0.000670696
Did not meet early stopping. Best iteration is:
[56]	valid's multi_logloss: 0.0946995 + 0.00253891	valid's macro_pr_auc: 0.995619 + 0.000173224
optuna_optimize took 8815.564 seconds
[I 2026-08-17 21:46:21,762] Trial 8 finished with value: 0.9956194798908115 and parameters: {'n_estimators': 56, 'learning_rate': 0.07620098886665848, 'num_leaves': 89}. Best is trial 4 with value: 0.9957873359780282.
Training until validation scores don't improve for 50 rounds
Did not meet early stopping. Best iteration is:
[63]	valid's multi_logloss: 0.117957 + 0.00291192	valid's macro_pr_auc: 0.99465 + 0.000215719
optuna_optimize took 8967.402 seconds
[I 2026-08-17 21:48:53,525] Trial 3 finished with value: 0.9946496793909642 and parameters: {'n_estimators': 63, 'learning_rate': 0.05212541690619412, 'num_leaves': 85}. Best is trial 4 with value: 0.9957873359780282.
Training until validation scores don't improve for 50 rounds
[70]	valid's multi_logloss: 0.0826187 + 0.00233865	valid's macro_pr_auc: 0.996293 + 0.000156887
[60]	valid's multi_logloss: 0.0982958 + 0.00258764	valid's macro_pr_auc: 0.995491 + 0.000197709
[20]	valid's multi_logloss: 0.430135 + 0.00293044	valid's macro_pr_auc: 0.987189 + 0.000600902
[60]	valid's multi_logloss: 0.108384 + 0.00235525	valid's macro_pr_auc: 0.995027 + 0.000149797
[30]	valid's multi_logloss: 0.276985 + 0.00362005	valid's macro_pr_auc: 0.989187 + 0.000506946
[70]	valid's multi_logloss: 0.0834137 + 0.00165122	valid's macro_pr_auc: 0.996247 + 0.000102893
[10]	valid's multi_logloss: 0.861004 + 0.00186755	valid's macro_pr_auc: 0.978846 + 0.000774645
Did not meet early stopping. Best iteration is:
[57]	valid's multi_logloss: 0.0914794 + 0.00225844	valid's macro_pr_auc: 0.995739 + 0.0001275
optuna_optimize took 9828.409 seconds
[I 2026-08-17 22:03:14,576] Trial 1 finished with value: 0.995738588497044 and parameters: {'n_estimators': 57, 'learning_rate': 0.07995035898080254, 'num_leaves': 89}. Best is trial 4 with value: 0.9957873359780282.
[30]	valid's multi_logloss: 0.281033 + 0.00347236	valid's macro_pr_auc: 0.989124 + 0.000498355
Training until validation scores don't improve for 50 rounds
[10]	valid's multi_logloss: 0.83176 + 0.00187622	valid's macro_pr_auc: 0.981493 + 0.000787974
[70]	valid's multi_logloss: 0.101666 + 0.00259758	valid's macro_pr_auc: 0.995342 + 0.000187161
[70]	valid's multi_logloss: 0.0861785 + 0.00224177	valid's macro_pr_auc: 0.996096 + 0.000140193
[10]	valid's multi_logloss: 0.628525 + 0.00267056	valid's macro_pr_auc: 0.981415 + 0.000743695
[20]	valid's multi_logloss: 0.467183 + 0.00246891	valid's macro_pr_auc: 0.985398 + 0.000585796
[40]	valid's multi_logloss: 0.195303 + 0.00369269	valid's macro_pr_auc: 0.991566 + 0.000429977
[80]	valid's multi_logloss: 0.0777221 + 0.00234563	valid's macro_pr_auc: 0.996628 + 0.000147506
Did not meet early stopping. Best iteration is:
[78]	valid's multi_logloss: 0.0794603 + 0.00164666	valid's macro_pr_auc: 0.996506 + 0.000101664
optuna_optimize took 10978.668 seconds
[I 2026-08-17 22:22:24,815] Trial 2 finished with value: 0.9965062789389671 and parameters: {'n_estimators': 78, 'learning_rate': 0.07771723630005983, 'num_leaves': 78}. Best is trial 2 with value: 0.9965062789389671.
[40]	valid's multi_logloss: 0.198026 + 0.0034891	valid's macro_pr_auc: 0.991509 + 0.000398255
Training until validation scores don't improve for 50 rounds
[30]	valid's multi_logloss: 0.265605 + 0.0031951	valid's macro_pr_auc: 0.990236 + 0.00044728
[70]	valid's multi_logloss: 0.0886578 + 0.00250478	valid's macro_pr_auc: 0.995967 + 0.000187134
[10]	valid's multi_logloss: 0.471412 + 0.00283721	valid's macro_pr_auc: 0.982962 + 0.000616902
[70]	valid's multi_logloss: 0.0956406 + 0.00230322	valid's macro_pr_auc: 0.995618 + 0.000121993
[20]	valid's multi_logloss: 0.440537 + 0.00244828	valid's macro_pr_auc: 0.987337 + 0.000587969
[20]	valid's multi_logloss: 0.302911 + 0.00299115	valid's macro_pr_auc: 0.988265 + 0.000500106
[80]	valid's multi_logloss: 0.0920342 + 0.00265169	valid's macro_pr_auc: 0.995797 + 0.000187787
[80]	valid's multi_logloss: 0.0803662 + 0.00214619	valid's macro_pr_auc: 0.996449 + 0.000139064
Did not meet early stopping. Best iteration is:
[72]	valid's multi_logloss: 0.0937567 + 0.00224142	valid's macro_pr_auc: 0.995703 + 0.000124509
optuna_optimize took 11885.607 seconds
[I 2026-08-17 22:37:31,758] Trial 6 finished with value: 0.9957028876232261 and parameters: {'n_estimators': 72, 'learning_rate': 0.05937131325721694, 'num_leaves': 91}. Best is trial 2 with value: 0.9965062789389671.
[50]	valid's multi_logloss: 0.151202 + 0.00316622	valid's macro_pr_auc: 0.993153 + 0.000323638
Training until validation scores don't improve for 50 rounds
Did not meet early stopping. Best iteration is:
[81]	valid's multi_logloss: 0.0799272 + 0.0022457	valid's macro_pr_auc: 0.99648 + 0.000147937
[30]	valid's multi_logloss: 0.29358 + 0.00311238	valid's macro_pr_auc: 0.98889 + 0.000532789
optuna_optimize took 12021.000 seconds
[I 2026-08-17 22:39:47,099] Trial 0 finished with value: 0.996479962094298 and parameters: {'n_estimators': 81, 'learning_rate': 0.07108032767628408, 'num_leaves': 86}. Best is trial 2 with value: 0.9965062789389671.
Training until validation scores don't improve for 50 rounds
Did not meet early stopping. Best iteration is:
[88]	valid's multi_logloss: 0.0753037 + 0.00241932	valid's macro_pr_auc: 0.996813 + 0.000142354
optuna_optimize took 12171.892 seconds
[I 2026-08-17 22:42:18,048] Trial 7 finished with value: 0.9968129192764079 and parameters: {'n_estimators': 88, 'learning_rate': 0.0800146983033735, 'num_leaves': 75}. Best is trial 7 with value: 0.9968129192764079.
[50]	valid's multi_logloss: 0.15314 + 0.00298498	valid's macro_pr_auc: 0.993087 + 0.000272071
Training until validation scores don't improve for 50 rounds
[20]	valid's multi_logloss: 0.217077 + 0.00306834	valid's macro_pr_auc: 0.990055 + 0.000516128
Did not meet early stopping. Best iteration is:
[77]	valid's multi_logloss: 0.0839349 + 0.00243752	valid's macro_pr_auc: 0.99623 + 0.000177239
optuna_optimize took 12752.213 seconds
[I 2026-08-17 22:51:58,669] Trial 10 finished with value: 0.996229509500257 and parameters: {'n_estimators': 77, 'learning_rate': 0.06699287478595047, 'num_leaves': 90}. Best is trial 7 with value: 0.9968129192764079.
[10]	valid's multi_logloss: 0.770197 + 0.002231	valid's macro_pr_auc: 0.980639 + 0.000641278
Training until validation scores don't improve for 50 rounds
[30]	valid's multi_logloss: 0.186608 + 0.00302468	valid's macro_pr_auc: 0.991746 + 0.000396193
[40]	valid's multi_logloss: 0.185553 + 0.00320681	valid's macro_pr_auc: 0.99235 + 0.000366832
[10]	valid's multi_logloss: 0.486401 + 0.00321648	valid's macro_pr_auc: 0.984603 + 0.000779166
[10]	valid's multi_logloss: 0.466417 + 0.00264458	valid's macro_pr_auc: 0.984257 + 0.000711392
[60]	valid's multi_logloss: 0.125485 + 0.00317427	valid's macro_pr_auc: 0.99419 + 0.000293118
[40]	valid's multi_logloss: 0.206653 + 0.00326487	valid's macro_pr_auc: 0.991318 + 0.000459862
[10]	valid's multi_logloss: 0.500614 + 0.0028289	valid's macro_pr_auc: 0.983967 + 0.00068513
[30]	valid's multi_logloss: 0.271852 + 0.00302486	valid's macro_pr_auc: 0.990293 + 0.000495035
[90]	valid's multi_logloss: 0.0856314 + 0.00253069	valid's macro_pr_auc: 0.996141 + 0.000167732
[60]	valid's multi_logloss: 0.126952 + 0.00267541	valid's macro_pr_auc: 0.994133 + 0.000220296
[30]	valid's multi_logloss: 0.140036 + 0.00317761	valid's macro_pr_auc: 0.993196 + 0.000389674
[20]	valid's multi_logloss: 0.39665 + 0.00331262	valid's macro_pr_auc: 0.986955 + 0.000613998
[40]	valid's multi_logloss: 0.13601 + 0.00289572	valid's macro_pr_auc: 0.993723 + 0.000329551
[20]	valid's multi_logloss: 0.219676 + 0.00293475	valid's macro_pr_auc: 0.990725 + 0.00048643
[70]	valid's multi_logloss: 0.109027 + 0.00297108	valid's macro_pr_auc: 0.99493 + 0.000218826
[20]	valid's multi_logloss: 0.21147 + 0.00266795	valid's macro_pr_auc: 0.990666 + 0.000482989
[50]	valid's multi_logloss: 0.158839 + 0.00305976	valid's macro_pr_auc: 0.992964 + 0.000356176
[50]	valid's multi_logloss: 0.142911 + 0.00291629	valid's macro_pr_auc: 0.993768 + 0.000274478
[40]	valid's multi_logloss: 0.108178 + 0.00348971	valid's macro_pr_auc: 0.994789 + 0.000351376
[70]	valid's multi_logloss: 0.11019 + 0.00255455	valid's macro_pr_auc: 0.994887 + 0.000186032
[20]	valid's multi_logloss: 0.228042 + 0.00300136	valid's macro_pr_auc: 0.990325 + 0.000510453
Did not meet early stopping. Best iteration is:
[54]	valid's multi_logloss: 0.145981 + 0.00288304	valid's macro_pr_auc: 0.993456 + 0.000307079
optuna_optimize took 6438.983 seconds
[I 2026-08-17 23:33:41,165] Trial 15 finished with value: 0.9934562402473605 and parameters: {'n_estimators': 54, 'learning_rate': 0.05143131848841922, 'num_leaves': 67}. Best is trial 7 with value: 0.9968129192764079.
[100]	valid's multi_logloss: 0.0810406 + 0.00246974	valid's macro_pr_auc: 0.996406 + 0.00015352
Did not meet early stopping. Best iteration is:
[100]	valid's multi_logloss: 0.0810406 + 0.00246974	valid's macro_pr_auc: 0.996406 + 0.00015352
optuna_optimize took 15335.144 seconds
[I 2026-08-17 23:35:01,331] Trial 9 finished with value: 0.9964055048235283 and parameters: {'n_estimators': 100, 'learning_rate': 0.05503187893879206, 'num_leaves': 90}. Best is trial 7 with value: 0.9968129192764079.
[30]	valid's multi_logloss: 0.244523 + 0.0033109	valid's macro_pr_auc: 0.990257 + 0.000418105
Training until validation scores don't improve for 50 rounds
[40]	valid's multi_logloss: 0.189235 + 0.00315709	valid's macro_pr_auc: 0.992358 + 0.000386171
[50]	valid's multi_logloss: 0.11047 + 0.00245906	valid's macro_pr_auc: 0.994854 + 0.000263526
Training until validation scores don't improve for 50 rounds
[80]	valid's multi_logloss: 0.0980773 + 0.00269266	valid's macro_pr_auc: 0.995463 + 0.000178275
Did not meet early stopping. Best iteration is:
[77]	valid's multi_logloss: 0.101846 + 0.00252974	valid's macro_pr_auc: 0.995288 + 0.000191993
optuna_optimize took 8942.686 seconds
[I 2026-08-17 23:44:02,183] Trial 13 finished with value: 0.9952883952206338 and parameters: {'n_estimators': 77, 'learning_rate': 0.053404335343278396, 'num_leaves': 66}. Best is trial 7 with value: 0.9968129192764079.
Training until validation scores don't improve for 50 rounds
[30]	valid's multi_logloss: 0.138 + 0.00259303	valid's macro_pr_auc: 0.993566 + 0.000301293
[30]	valid's multi_logloss: 0.135026 + 0.00252446	valid's macro_pr_auc: 0.993548 + 0.00033626
[50]	valid's multi_logloss: 0.0924498 + 0.00333569	valid's macro_pr_auc: 0.99565 + 0.000273293
[10]	valid's multi_logloss: 0.493695 + 0.0033026	valid's macro_pr_auc: 0.984066 + 0.000820732
[10]	valid's multi_logloss: 0.477961 + 0.00277336	valid's macro_pr_auc: 0.984234 + 0.000560936
[30]	valid's multi_logloss: 0.14314 + 0.00273936	valid's macro_pr_auc: 0.993326 + 0.000313493
Did not meet early stopping. Best iteration is:
[86]	valid's multi_logloss: 0.0932034 + 0.00269544	valid's macro_pr_auc: 0.995707 + 0.000175714
optuna_optimize took 9758.294 seconds

#### Визуализация optuna:
1) Сравнение важности гиперпараметров
2) Отрисовка контура оптимизации. Помогает выбрать направление дальнейшей оптимизации в сторону "темных" областей

In [3]:
from optuna.visualization import plot_param_importances

plot_param_importances(study)

In [4]:
from optuna.visualization import plot_contour

plot_contour(study)

#### Применение найденных лучших гиперпараметров:

In [5]:
with memory_check():
    alter_title = f'{LGBM}_tuned'
    processor.calculate({
        LGBM : {
            "n_estimators": 99,
            "learning_rate": 0.09948,
            "num_leaves": 81,
            'alter_title': alter_title
        },
    })
    processor.report(alter_title)
    processor.pick_model(alter_title)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.127459 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 108649
[LightGBM] [Info] Number of data points in the train set: 56000, number of used features: 627
[LightGBM] [Info] Start training from score -2.316612
[LightGBM] [Info] Start training from score -2.184485
[LightGBM] [Info] Start training from score -2.304015
[LightGBM] [Info] Start training from score -2.282607
[LightGBM] [Info] Start training from score -2.328086
[LightGBM] [Info] Start training from score -2.405963
[LightGBM] [Info] Start training from score -2.320422
[LightGBM] [Info] Start training from score -2.261649
[LightGBM] [Info] Start training from score -2.327903
[LightGBM] [Info] Start training from score -2.308495

	light_gradient_boosting_machine_tuned

              precision  recall  f1-score   support
0                 0.980   0.991     0.986  1381.000
1                 0.989   0.985     0.987  1575.000
2                 0.976   0.974     0.975  1398.000
3                 0.980   0.978     0.979  1428.000
4                 0.978   0.971     0.974  1365.000
5                 0.985   0.971     0.978  1263.000
6                 0.981   0.984     0.983  1375.000
7                 0.975   0.979     0.977  1459.000
8                 0.966   0.979     0.973  1365.000
9                 0.968   0.963     0.965  1391.000
accuracy          0.978   0.978     0.978     0.978
macro avg         0.978   0.978     0.978 14000.000
weighted avg      0.978   0.978     0.978 14000.000

Memory Increased by: 593.18 MB

#### Мини-репорт:

In [6]:
dec_tr = next((model for model in processor.models if model.title == LGBM), None)
dec_tr_tuned = next((model for model in processor.models if model.title == alter_title), None)

print(f"{LGBM} : {alter_title} >> {dec_tr.pr_auc} : {dec_tr_tuned.pr_auc}")

light_gradient_boosting_machine : light_gradient_boosting_machine_tuned >> 0.9963686913530966 : 0.996779173100143